export const FETCH_FORKS_REQUEST = '@FETCH_FORKS_REQUEST'
export const FETCH_FORKS_SUCCESS = '@FETCH_FORKS_SUCCESS'
export const FETCH_FORKS_FAILURE = '@FETCH_FORKS_FAILURE'

export const FETCH_REPOS_REQUEST = '@FETCH_REPOS_REQUEST'
export const FETCH_REPOS_SUCCESS = '@FETCH_REPOS_SUCCESS'
export const FETCH_REPOS_FAILURE = '@FETCH_REPOS_FAILURE'
